-- Companies
CREATE TABLE public.companies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL UNIQUE,
    is_active boolean,
    name character varying(255) NOT NULL UNIQUE,
    phone character varying(255) NOT NULL,
    plan_type character varying(255),
    CONSTRAINT companies_plan_type_check CHECK (((plan_type)::text = ANY ((ARRAY['FREE'::character varying, 'PRO'::character varying, 'ENTERPRISE'::character varying])::text[])))
);

-- Users
CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL UNIQUE,
    is_active boolean,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    company_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'HR_ADMIN'::character varying, 'HR_MANAGER'::character varying, 'EMPLOYEE'::character varying])::text[]))),
    CONSTRAINT fkin8gn4o1hpiwe6qe4ey7ykwq7 FOREIGN KEY (company_id) REFERENCES public.companies(id)
);

-- Departments
CREATE TABLE public.departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    description character varying(255),
    is_active boolean,
    name character varying(255) NOT NULL,
    company_id bigint NOT NULL,
    CONSTRAINT fkoq64wrpwbvd4lq19c3qyxykl0 FOREIGN KEY (company_id) REFERENCES public.companies(id)
);

-- Employees
CREATE TABLE public.employees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    designation character varying(255),
    email character varying(255) NOT NULL UNIQUE,
    employee_code character varying(255) UNIQUE,
    first_name character varying(255) NOT NULL,
    joining_date date,
    last_name character varying(255) NOT NULL,
    monthly_salary double precision,
    phone character varying(255),
    status character varying(255),
    company_id bigint NOT NULL,
    department_id bigint,
    reporting_manager_id bigint,
    CONSTRAINT employees_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'ON_LEAVE'::character varying, 'TERMINATED'::character varying])::text[]))),
    CONSTRAINT fk1ekpcbo0lmdx6ou8e3fh9j4lq FOREIGN KEY (company_id) REFERENCES public.companies(id),
    CONSTRAINT fkgy4qe3dnqrm3ktd76sxp7n4c2 FOREIGN KEY (department_id) REFERENCES public.departments(id),
    CONSTRAINT fkj5dawmyfw3dmtixnsrr6cbk63 FOREIGN KEY (reporting_manager_id) REFERENCES public.employees(id)
);

-- Attendance
CREATE TABLE public.attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_date date NOT NULL,
    check_in_time timestamp(6) without time zone,
    check_out_time timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    marked_by_hr boolean,
    status character varying(255) NOT NULL,
    working_hours double precision,
    company_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT attendance_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'HALF_DAY'::character varying, 'ON_LEAVE'::character varying])::text[]))),
    CONSTRAINT uk21b5aixlcr00rk9odp8g3x7h0 UNIQUE (employee_id, attendance_date),
    CONSTRAINT fk9uuahi49m8mmxjgsler5ps1w0 FOREIGN KEY (company_id) REFERENCES public.companies(id),
    CONSTRAINT fkb48lmkou5j4rvde9sr88bqgjw FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);

-- Leave types
CREATE TABLE public.leave_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    description character varying(255),
    is_active boolean,
    max_days_per_year integer,
    name character varying(255) NOT NULL,
    company_id bigint NOT NULL,
    CONSTRAINT fkfccywx9f595wkh0n07p39g1ix FOREIGN KEY (company_id) REFERENCES public.companies(id)
);

-- Leave balances
CREATE TABLE public.leave_balances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remaining_days integer,
    total_days integer,
    used_days integer,
    year integer NOT NULL,
    employee_id bigint NOT NULL,
    leave_type_id bigint NOT NULL,
    CONSTRAINT fkmvepkwsegu6bt3ps5rfh1dx92 FOREIGN KEY (employee_id) REFERENCES public.employees(id),
    CONSTRAINT fk86791wotycqa54js45s9396wy FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id)
);

-- Leave requests
CREATE TABLE public.leave_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    from_date date NOT NULL,
    manager_comment character varying(255),
    reason character varying(255),
    reviewed_at timestamp(6) without time zone,
    status character varying(255),
    to_date date NOT NULL,
    total_days integer,
    company_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    leave_type_id bigint NOT NULL,
    reviewed_by bigint,
    CONSTRAINT leave_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT fktp1fia7rnqiqmsgr8270ilpvf FOREIGN KEY (company_id) REFERENCES public.companies(id),
    CONSTRAINT fkrxff2xg1kffbjfh5maxwoqyhw FOREIGN KEY (employee_id) REFERENCES public.employees(id),
    CONSTRAINT fk26il0qrl79p6etqwn0ae6l43b FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id),
    CONSTRAINT fkm6br6lc65loui2q8s547hqyv7 FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);

-- Payroll
CREATE TABLE public.payroll (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    absent_days bigint,
    deduction_amount double precision,
    generated_at timestamp(6) without time zone,
    half_days bigint,
    is_paid boolean,
    month integer NOT NULL,
    monthly_salary double precision NOT NULL,
    net_salary double precision,
    present_days bigint,
    year integer NOT NULL,
    company_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT ukocpx6rl7m6n4h3oetx1055fhk UNIQUE (employee_id, month, year),
    CONSTRAINT fk1u50wuqmwakvdto9vgckeugcu FOREIGN KEY (company_id) REFERENCES public.companies(id),
    CONSTRAINT fko65c0oqf6hr6eka6xtty7ccc FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);