--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    attendance_date date NOT NULL,
    check_in_time timestamp(6) without time zone,
    check_out_time timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    marked_by_hr boolean,
    status character varying(255) NOT NULL,
    working_hours double precision,
    company_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT attendance_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'HALF_DAY'::character varying, 'ON_LEAVE'::character varying])::text[])))
);


--
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    is_active boolean,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    plan_type character varying(255),
    CONSTRAINT companies_plan_type_check CHECK (((plan_type)::text = ANY ((ARRAY['FREE'::character varying, 'PRO'::character varying, 'ENTERPRISE'::character varying])::text[])))
);


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    is_active boolean,
    name character varying(255) NOT NULL,
    company_id bigint NOT NULL
);


--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    designation character varying(255),
    email character varying(255) NOT NULL,
    employee_code character varying(255),
    first_name character varying(255) NOT NULL,
    joining_date date,
    last_name character varying(255) NOT NULL,
    monthly_salary double precision,
    phone character varying(255),
    status character varying(255),
    company_id bigint NOT NULL,
    department_id bigint,
    reporting_manager_id bigint,
    CONSTRAINT employees_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'ON_LEAVE'::character varying, 'TERMINATED'::character varying])::text[])))
);


--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_balances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leave_balances (
    id bigint NOT NULL,
    remaining_days integer,
    total_days integer,
    used_days integer,
    year integer NOT NULL,
    employee_id bigint NOT NULL,
    leave_type_id bigint NOT NULL
);


--
-- Name: leave_balances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.leave_balances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_balances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leave_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    from_date date NOT NULL,
    manager_comment character varying(255),
    reason character varying(255),
    reviewed_at timestamp(6) without time zone,
    status character varying(255),
    to_date date NOT NULL,
    total_days integer,
    company_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    leave_type_id bigint NOT NULL,
    reviewed_by bigint,
    CONSTRAINT leave_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: leave_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.leave_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leave_types (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    is_active boolean,
    max_days_per_year integer,
    name character varying(255) NOT NULL,
    company_id bigint NOT NULL
);


--
-- Name: leave_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.leave_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payroll; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payroll (
    id bigint NOT NULL,
    absent_days bigint,
    deduction_amount double precision,
    generated_at timestamp(6) without time zone,
    half_days bigint,
    is_paid boolean,
    month integer NOT NULL,
    monthly_salary double precision NOT NULL,
    net_salary double precision,
    present_days bigint,
    year integer NOT NULL,
    company_id bigint NOT NULL,
    employee_id bigint NOT NULL
);


--
-- Name: payroll_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payroll ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payroll_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    is_active boolean,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    company_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'HR_ADMIN'::character varying, 'HR_MANAGER'::character varying, 'EMPLOYEE'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: leave_balances leave_balances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_balances
    ADD CONSTRAINT leave_balances_pkey PRIMARY KEY (id);


--
-- Name: leave_requests leave_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_requests
    ADD CONSTRAINT leave_requests_pkey PRIMARY KEY (id);


--
-- Name: leave_types leave_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_types
    ADD CONSTRAINT leave_types_pkey PRIMARY KEY (id);


--
-- Name: payroll payroll_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT payroll_pkey PRIMARY KEY (id);


--
-- Name: attendance uk21b5aixlcr00rk9odp8g3x7h0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT uk21b5aixlcr00rk9odp8g3x7h0 UNIQUE (employee_id, attendance_date);


--
-- Name: companies uk50ygfritln653mnfhxucoy8up; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT uk50ygfritln653mnfhxucoy8up UNIQUE (name);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: employees uketqhw9qqnad1kyjq3ks1glw8x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT uketqhw9qqnad1kyjq3ks1glw8x UNIQUE (employee_code);


--
-- Name: employees ukj9xgmd0ya5jmus09o0b8pqrpb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT ukj9xgmd0ya5jmus09o0b8pqrpb UNIQUE (email);


--
-- Name: payroll ukocpx6rl7m6n4h3oetx1055fhk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT ukocpx6rl7m6n4h3oetx1055fhk UNIQUE (employee_id, month, year);


--
-- Name: companies ukqjgsqh1oq7xhof2tdte9l7e2b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT ukqjgsqh1oq7xhof2tdte9l7e2b UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: employees fk1ekpcbo0lmdx6ou8e3fh9j4lq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk1ekpcbo0lmdx6ou8e3fh9j4lq FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: payroll fk1u50wuqmwakvdto9vgckeugcu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT fk1u50wuqmwakvdto9vgckeugcu FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: leave_requests fk26il0qrl79p6etqwn0ae6l43b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_requests
    ADD CONSTRAINT fk26il0qrl79p6etqwn0ae6l43b FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id);


--
-- Name: leave_balances fk86791wotycqa54js45s9396wy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_balances
    ADD CONSTRAINT fk86791wotycqa54js45s9396wy FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id);


--
-- Name: attendance fk9uuahi49m8mmxjgsler5ps1w0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fk9uuahi49m8mmxjgsler5ps1w0 FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: attendance fkb48lmkou5j4rvde9sr88bqgjw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkb48lmkou5j4rvde9sr88bqgjw FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: leave_types fkfccywx9f595wkh0n07p39g1ix; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_types
    ADD CONSTRAINT fkfccywx9f595wkh0n07p39g1ix FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: employees fkgy4qe3dnqrm3ktd76sxp7n4c2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fkgy4qe3dnqrm3ktd76sxp7n4c2 FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: users fkin8gn4o1hpiwe6qe4ey7ykwq7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkin8gn4o1hpiwe6qe4ey7ykwq7 FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: employees fkj5dawmyfw3dmtixnsrr6cbk63; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fkj5dawmyfw3dmtixnsrr6cbk63 FOREIGN KEY (reporting_manager_id) REFERENCES public.employees(id);


--
-- Name: leave_requests fkm6br6lc65loui2q8s547hqyv7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_requests
    ADD CONSTRAINT fkm6br6lc65loui2q8s547hqyv7 FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: leave_balances fkmvepkwsegu6bt3ps5rfh1dx92; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_balances
    ADD CONSTRAINT fkmvepkwsegu6bt3ps5rfh1dx92 FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: payroll fko65c0oqf6hr6eka6xtty7ccc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payroll
    ADD CONSTRAINT fko65c0oqf6hr6eka6xtty7ccc FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: departments fkoq64wrpwbvd4lq19c3qyxykl0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT fkoq64wrpwbvd4lq19c3qyxykl0 FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: leave_requests fkrxff2xg1kffbjfh5maxwoqyhw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_requests
    ADD CONSTRAINT fkrxff2xg1kffbjfh5maxwoqyhw FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: leave_requests fktp1fia7rnqiqmsgr8270ilpvf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_requests
    ADD CONSTRAINT fktp1fia7rnqiqmsgr8270ilpvf FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- PostgreSQL database dump complete
--

