# App
spring.application.name=hrms

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/hrms_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Server
server.port=8080

# Super Admin (seeded on startup if not already present)
app.superadmin.email=${SUPERADMIN_EMAIL:superadmin@hrms.com}
app.superadmin.password=${SUPERADMIN_PASSWORD}

# Swagger / OpenAPI
springdoc.swagger-ui.enabled=true
# JSF / PrimeFaces (JoinFaces)
joinfaces.faces.project-stage=Development
joinfaces.primefaces.theme=saga
joinfaces.faces.state-saving-method=server